name: Develop Build

on:
  workflow_dispatch:
  pull_request:
  push:
      branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop
        
    - name: Checkout Maple
      uses: actions/checkout@v3
      with:
        path: Maple
        ref: develop
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          7.0.x
    
    - name: Build Maple
      run: dotnet build -c Release Maple/Source/Maple.sln
