name: NuGet Package Creation

on:
  workflow_dispatch:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"

env:
  version: '0.90.0'
  token: ${{ secrets.NUGET_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from env.version
      run: echo "VERSION=${{ env.version }}" >> $GITHUB_ENV
      
    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.DataLoggers.SensorReading
        path: Source/Meadow.Foundation.Libraries_and_Frameworks/DataLoggers.SensorReading/Driver/DataLoggers.SensorReading.csproj
        version: ${{ env.version }}
        token: ${{ env.token }}

    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.DataLoggers.ThingSpeak
        path: Source/Meadow.Foundation.Libraries_and_Frameworks/DataLoggers.ThingSpeak/Driver/DataLoggers.ThingSpeak.csproj
        version: ${{ env.version }}
        token: ${{ env.token }}

#    - name: Build Maple
#      run: dotnet build -c Release src/Server/Web.Maple.MapleServer.csproj /p:Version=${VERSION}
#    - name: Package maple
#      run: dotnet pack -c Release src/Server/Web.Maple.MapleServer.csproj /p:Version=${VERSION} --output .
#    - name: Push Maple to NuGet
#      run: dotnet nuget push Meadow.Foundation.Web.Maple.Server.${VERSION}.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}
#      env:
#        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
