name: NuGet Package Creation

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
    - name: Build Maple
      run: dotnet build -c Release src/Server/Web.Maple.MapleServer.csproj /p:Version=${VERSION}
    - name: Package maple
      run: dotnet pack -c Release src/Server/Web.Maple.MapleServer.csproj /p:Version=${VERSION} --output .
    - name: Push Maple to NuGet
      run: dotnet nuget push Meadow.Foundation.Web.Maple.Server.${VERSION}.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
